allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@keystatic/core@0.6.6'
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - arm64
    - x64
